# renamed-console-title: ""

# Set this to the maximum possible length of the console title
# only if renamed-console-title is not set to anything. If renamed-console-title
# is set to something, this does nothing.
max-console-title-length: 30

disable-console-rename: false

disable-player-head-drop: false
