main: ca.anthonyting.personalplugins.Main
name: Custom
version: "0.1"
api-version: "1.18"
softdepend:
  - EmojiChat
commands:
  forcebackup:
    description: Copies and overwrites files at directory specified in config
    permission: personalplugins.forcebackup
  playtime:
    description: Get the playtime of yourself or another player
    permission: personalplugins.playtime
    usage: "Usage: /<command> [player]"
  getstat:
    description: Get a stat of yourself or another player
    permission: personalplugins.getstat
    usage: "Usage: /<command> [stat] [player]"
  emoji:
    description: Send a message with an emoji
    permission: personalplugins.emoji
    usage: "Usage: /<command> text [emoji] text"
permissions:
  personalplugins.forcebackup:
    description: Allows forcebackup
    default: op
  personalplugins.playtime:
    description: Allows playtime
    default: true
  personalplugins.getstat:
    description: Allows getstat
    default: true
  personalplugins.emoji:
    description: Allows emoji messages
    default: true
  personalplugins.*:
    description: Wildcard permission
    default: op
    children:
      personalplugins.forcebackup: true