main: ca.anthonyting.personalplugins.Main
name: Custom
version: "0.1"
api-version: "1.15"
commands:
  forcebackup:
    description: Copies and overwrites files at directory specified in config
    permission: personalplugins.forcebackup
  playtime:
    description: Get the playtime of yourself or another player
    permission: personalplugins.playtime
    usage: /<command> [player]
permissions:
  personalplugins.forcebackup:
    description: Allows forcebackup
    default: op
  personalplugins.playtime:
    description: Allows playtime
    default: true
  personalplugins.*:
    description: Wildcard permission
    default: op
    children:
      personalplugins.forcebackup: true